# 1. Use an official Bun image as the base
FROM oven/bun:1 AS base

# 2. Set a working directory
WORKDIR /app

# 3. Copy package.json, bun.lockb first
# This helps leverage Docker's layer caching. If these files don't change,
# Docker can reuse the layer where dependencies are installed.
COPY package.json bun.lockb ./

# 4. Install dependencies
# Using --frozen-lockfile for reproducible builds.
# If this causes issues (e.g., if bun.lockb is not perfectly in sync),
# you might fall back to `bun install`, but it's less ideal.
RUN bun install --frozen-lockfile

# 5. Copy the rest of the application source code
# This includes index.ts, db.ts, and any other backend files.
# It's placed after dependency installation so that code changes
# don't invalidate the dependency layer.
COPY . .
# Note: .dockerignore should prevent node_modules, .git, etc., from being copied.

# 6. Copy the db.sqlite file into the image
# For a standalone Dockerfile, this includes a default database.
# In a docker-compose setup, this path would typically be a volume mount point.
# Ensure db.sqlite exists in your project root or adjust the COPY source path.
# If db.sqlite is generated by the app on first run and you don't have one to copy,
# the app will create it inside the container. If you have a pre-seeded one, copy it.
# COPY db.sqlite ./db.sqlite
# Assuming the application creates db.sqlite if it doesn't exist, based on db.ts:
# `const db = new Database(dbFile, { create: true });`
# So, explicitly copying might not be strictly necessary if starting fresh is okay.
# However, if you have an existing db.sqlite with schema/data, uncomment the COPY line.
# For this exercise, let's assume the app creates it.

# 7. Expose the port the backend application listens on
# This should match the port in your index.ts (e.g., 3000)
EXPOSE 3000

# 8. Define the command to run the application
# This command will be executed when the container starts.
# Replace 'index.ts' with the actual path to your main backend file if different.
# Ensure your index.ts or package.json script handles running in a non-dev environment.
# CMD ["bun", "run", "index.ts"]
# Or if you have a specific start script in package.json:
# CMD ["bun", "run", "start"]
# Assuming direct execution of index.ts for production-like startup
# The `index.ts` is already set up to listen when NODE_ENV is not 'test'.
# We might need to set NODE_ENV to 'production' or similar for the container.
ENV NODE_ENV=production
CMD ["bun", "index.ts"]
